version: "3.6"

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=${MONGO_USER}
      - DATABASE_PASSWORD=${MONGO_PASSWORD}
      - HOST=strapi.vinnocenti.com
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.strapi.port=1337"
        - "traefik.docker.network=traefik_web"
        - "traefik.frontend.rule=Host:strapi.vinnocenti.com"
    volumes:
      - /opt/strapi-app:/usr/src/api/strapi-app
      - /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    networks:
      - web

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/mongo/db:/data/db
    networks:
      - web

networks:
  web:
    external:
      name: traefik_web
